### ISSUE TITLE
Reports that generate errors

### ISSUE THREAD

**Issue by MalcolmShazell** [epimorphics/standard-reports-ui#4]
these are the reports that victor created that generated errors last week

|  Average   |  District           |  South Lakeland  |                   |  Q2 2015   |  Any     |
|  Average   |  Postcode Sector    |  LA8 9           |                   |  Q2 2015   |  Any     |
|  Banded    |  District           |  South Lakeland  |                   |  Q2 2015   |  Any     |
|  Banded    |  Postcode Sector    |  LA8 9           |                   |  Q2 2015   |  Any     |

verified the second one myself just to make sure it wasn't something to do with last week (nothing works properly between Christmas and New Year) and do indeed get the 'We're sorry, but something went wrong.' message

**Comment by ijdickinson** [comment]
Fix deployed to dev server

**Comment by MalcolmShazell** [comment]
i'm still getting the same problem with the LA8 9 postcode search - south Lakeland is now working

**Comment by MalcolmShazell** [comment]
both are working fine now
